### ISSUE TITLE
It does's display any list of workspaces when it hit "workspaces(2) on left menu at Eclipse Che window.

### ISSUE THREAD

**Issue by joshuawilson** [redhat-developer/rh-che#105]
_From @danieloh30 on June 12, 2017 8:14_

There is no changes in right window when I hit workspace menu in Eclipse Che window even though there is 2 workspaces like "workspaces(2)" as below screenshot. Normally it expects the details of workspace list.
![screenshot from 2017-06-12 17-08-51](https://user-images.githubusercontent.com/14066977/27024582-08800958-4f92-11e7-80a4-60d9b7c6d7db.png)

_Copied from original issue: openshiftio/openshift.io#220_

**Comment by ibuziuk** [comment]
Even though this looks like a bug, note that Dashboard will not be exposed to the end-user and in order to get the list of workspaces "Codebases" view should be used in openshift.io

**Comment by joshuawilson** [comment]
That is what I thought. I didn't know the dashboard even worked in our version of Che.

**Comment by l0rd** [comment]
@joshuawilson I think that the real issue here is that users still need Che dashboard to list, stop and delete existing workspaces. Is there a github issue for adding these capabilities to codebase? It would be useful to link it here.

However this is a duplicate of [CHE-285](https://issues.jboss.org/browse/CHE-285). There is a workaround (cf. https://youtu.be/ZxmaGv2Jhu8) and as @ibuziuk mentioned this issue has low priority because on osio we are going to remove the dashboard.

But I don't want to close it because we are distributing a standalone version of Che (`fabric8-ide`) too with a fully working dashboard.

**Comment by joshuawilson** [comment]
@l0rd I don't see an issue related to this, you can add one here https://github.com/fabric8io/fabric8-ui/issues

**Comment by l0rd** [comment]
This has been fixed by https://github.com/redhat-developer/rh-che/commit/8950bf1f3936fdd17b003fbe11e69f18cdfe227d
