### ISSUE TITLE
Is it possible to separate client-side and server-side Theia IDE load?

### ISSUE THREAD

**Issue by amisevsk** [redhat-developer/rh-che#1060]
The Theia IDE continues to work even if the workspace pod is deleted -- you can scale the deployment to zero and back to one without breaking Theia (it just shows a yellow "disconnected" bar across the bottom 
![screenshot from 2018-11-13 09-51-34](https://user-images.githubusercontent.com/16168279/48421108-cb94c480-e729-11e8-94e7-ff887525cdaa.png)

However it seems that loading the client-side js does not occur until the workspace is fully started. Is it possible to do the client-side loading *while* the openshift resources are being created to save some time in startup?

**Comment by garagatyi** [comment]
@amisevsk I think it is exactly what @davidfestal was working on and was describing on our standups. Maybe it wasn't that obvious or maybe I misunderstood David.  
@davidfestal could you comment on that?

**Comment by davidfestal** [comment]
@garagatyi  I'm not sure that's exactly the same thing as what I'm working on if I understood correctly.

My work mainly consists in allowing the Theia Javascript bundle files (big JS files) to be:
- cached correctly (which implies having them available from a fixed URL instead of the always-changing workspace route URL)
- retrieved from a configured CDN when available from there, with a fallback to local versions (which implies changing the HTML page accordingly)
- pre-loaded into the browser cache from the HTML page of the workspace loader (= previous step), so that the first client-side loading and caching of these big JS files would occur while the Theia container is still starting on the server-side.

However, the idea of displaying the whole Theia application (with the HTML itself) in the browser before the server-side container initialization is finished was not really part of the work I'm currently doing even though it might be a continuation of it.

**Comment by garagatyi** [comment]
I'm not sure we can load client-side without having a server-side running. But, in any case, I thought that Angel was describing only caching of JS from ws loader or UD, not showing whole client side

**Comment by ibuziuk** [comment]
Closing in favour of https://github.com/eclipse/che/issues/14879 which should list all the optimizations related to workspace startup timing (N.B. on hosted che the startup is ~35 s atm)
