### ISSUE TITLE
Implement Github token provider that retrieves token from keycloak

### ISSUE THREAD

**Issue by sunix** [redhat-developer/rh-che#108]
at the moment, with https://github.com/redhat-developer/rh-che/pull/98 github token is set by platform and che-starter when a workspace starts. There are few issues with it:

- these tokens are stored in memory and having che-server restarted or coming back from idling would loose these tokens
- It is not recommended to expose this kind of api (according to oauth documentation)
- this won't work with multitenant

I would suggest to implement a custom tokenProvider that would ask to platform for the github key each time it can't find it and need it. It would use the keycloack token to access to it.

**Comment by gorkem** [comment]
@ibuziuk Is this different from what you already implemented?

**Comment by ibuziuk** [comment]
@gorkem this issue is different - what I did is just moved the API from che to our assembly, and this approach will not work for multitenant che-server

> I would suggest to implement a custom tokenProvider that would ask to platform for the github key each 
but we already have this API on che-server side [1] no need to call platform.

[1] https://github.com/redhat-developer/rh-che/blob/master/builds/fabric8-che/plugins/keycloak-plugin-token-provider/src/main/java/com/redhat/che/keycloak/token/provider/contoller/TokenController.java#L89

**Comment by skabashnyuk** [comment]
FYI https://github.com/eclipse/che/issues/5943

**Comment by l0rd** [comment]
This will be solved with the multi-user support in upstream Che
