### ISSUE TITLE
Workspaces are snapshotted on stop in OSIO

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/rh-che#109]
That's not the normal Eclipse Che behavior and it's probably an OpenShiftConnector bug. 
That has consequences in terms useless CPU and Storage consumption.

EDIT: The OpenShift connector doesn't really do the snapshot of the workspace so there is no resource consumptions issue. That's more about the message shown to the user being confusing. We should not say that the workspace has been snapshotted if it's not the case.

**Comment by sunix** [comment]
when iddling, we should be careful to keep builds artifact such as /home/user/.m2/repository and others user folders.

**Comment by l0rd** [comment]
@sunix that's a different issue. Maven local repository should be persisted in a PV. Snapshotting it is not a good idea: every snapshot would be of hundreds MB and there could be many thousands snapshots in a single day...

**Comment by l0rd** [comment]
But yeah I agree that from a UX perspective persisting maven repository is even more important than avoiding snapshotting.

**Comment by l0rd** [comment]
@amisevsk suggest that in OpenShift we do not really do a snapshots even if a pop up say that the image is being snapshotted. So the fix here would be not to say to users that a snapshot has been done when it's not the case. I have edited the description.

**Comment by amisevsk** [comment]
@l0rd I think snapshotting workspaces is just the default behavior in Che. We should try setting [`che.workspace.auto_snapshot=false`](https://github.com/eclipse/che/blob/b95d74c5bbc8a7b8e87ce4af16392b8acca2134b/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/codenvy/che.properties#L37) and see if this resolves the problem.

For context, on OSO, "snapshots" are just ImageStreamTags that are labelled according to the snapshot that *would* have been generated. This is done because if Che thinks it has a snapshot of a workspace, it will try to launch that image (e.g. `rhche/centos_jdk8:4ce024f` instead of `rhche/centos_jdk8:latest`).
