### ISSUE TITLE
[spike] Investigate complexity of enabling telemetry support in Che 7 and create list of sub-taks 

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1154]
before working on `Prepare the telemetry Che support for the Theia switch` https://github.com/redhat-developer/rh-che/issues/690 We need to understand the complexity and create subtasks. The outcome of this issue would be the list of sub-tasks that would be easy to prioritize and estimate

**Comment by davidfestal** [comment]
I'm nearly able to run the Analytics main component as a side-car light-weight REST service compiled natively with GraalVm and packaged as a `FROM scratch` docker image.
For there, the work mainly is:
- Finalize the telemetry Woopra server to run as a side with machine token injection to contact the Che server
- Specify a well-defined API to submit telemetry events to the REST endpoint (swagger API, somewhat standardized, so that telemetry implementations can be easily pluggable / replaceable)
- Reuse the code of the new service in the initial component in the WSAgent to delegate to the new service (to have something compatible with both Che6 and Che7).
- Provide a way to the retrieve the URL of the telemetry service (if one is setup) to other workspace components.
- Call this service from other components of various events (such as theia IDE for file edition, etc ...), terminal usage, command execution, etc ...

**Comment by ibuziuk** [comment]
@davidfestal do you think we can close this issue now ?

**Comment by davidfestal** [comment]
Yes, I think so.
