### ISSUE TITLE
Add working Che 7 factories to https://www.eclipse.org/che/getting-started/cloud/

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1355]
Add working Che 7 factories to https://www.eclipse.org/che/getting-started/cloud/. There should be at very least 3 Che 7 factories available

**Comment by nickboldt** [comment]
Why not use the actual Che 7 devfiles instead of a different pile of factories?

For example in my local minishift, I can do this:

http://che-che.192.168.99.112.nip.io/f?url=https://raw.githubusercontent.com/eclipse/che-devfile-registry/master/devfiles/java-web-spring/devfile.yaml

and voom, I get a workspace:

![image](https://user-images.githubusercontent.com/227597/61546656-d372da00-aa17-11e9-9769-0e4911c7ae7f.png)

**Comment by ibuziuk** [comment]
@nickboldt this is the plan - https://github.com/redhat-developer/rh-che/issues/1451
Closing in favour of https://github.com/redhat-developer/rh-che/issues/1451
