### ISSUE TITLE
Dashboard tests cause failing build

### ISSUE THREAD

**Issue by amisevsk** [redhat-developer/rh-che#1364]
**Issue problem:** 
Currently tests are disabled while building the dashboard, due to downstream changes (see https://github.com/redhat-developer/rh-che/pull/1362). We either need to port our downstream changes to upstream or figure out a fix so that tests can be re-enabled.
Aym, the tests are failing since rh-che dashboard makes unexpected calls which are not mocked in the upstream - https://github.com/redhat-developer/rh-che/blob/af99e3c307891bc63dc274f9b352224858fde3cc/assembly/fabric8-ide-dashboard-war/src/components/ide-fetcher/che-ide-fetcher.service.ts#L106-L126

**Comment by ibuziuk** [comment]
@amisevsk I would rather opt for porting downstream changes to the upstream

**Comment by amisevsk** [comment]
@davidfestal The relevant diff is [here](https://github.com/redhat-developer/rh-che/blob/af99e3c307891bc63dc274f9b352224858fde3cc/assembly/fabric8-ide-dashboard-war/src/components/ide-fetcher/che-ide-fetcher.service.ts#L106-L126) -- do you think it can be ported to upstream without issue?

**Comment by davidfestal** [comment]
@amisevsk Yes, I think they could be ported to upstream without issue, though the involved API call will always fail (gracefully afair) when not on `rh-che` at first.
In order to really benefit from Dashboard CDN-pre-fetching also for upstream, we should add the wsmaster plugin introduced in commit https://github.com/redhat-developer/rh-che/commit/6cb9308746e18e39c9bf0575ec57c8d17e6c5878#diff-d1c7cee2e326bd168cb76031bef4ef0c to upstream Che. This would also require adding the `skopeo` tool in the base Che server Docker image, which might require looking into licensing.

**Comment by ibuziuk** [comment]
Moving CDN related tests from downstream to upstream should still be a way to go. However, we might need to open a CQ for using `scopeo` in the upstream.

**Comment by ibuziuk** [comment]
Now there are no Hosted Che specific changes other than branding https://github.com/redhat-developer/rh-che/tree/master/assembly/fabric8-ide-dashboard-war/src/assets/branding 
Closing
