### ISSUE TITLE
Setting header Authorization: Internal allows bypassing keycloak on Che.

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#137]
see https://issues.jboss.org/browse/CHE-299

Making API requests with the header `Authorization: Internal` allows one to bypass keycloak validation; you can delete someone's workspaces from a plain bash terminal if you know their base url.

**Comment by ibuziuk** [comment]
@gorkem @amisevsk do you happen to remember why it was initially implemented to skip requests with `Authorization: Internal` in https://github.com/redhat-developer/rh-che/blob/master/builds/fabric8-che/plugins/keycloak-plugin-server/src/main/java/com/redhat/che/keycloak/server/KeycloakAuthenticationFilter.java#L60 ?

**Comment by amisevsk** [comment]
@ibuziuk It was necessary because internal requests don't have an authorization header and so get blocked. The header is added by [KeycloakHttpJsonRequestFactory](https://github.com/redhat-developer/rh-che/blob/master/builds/fabric8-che/plugins/keycloak-plugin-server/src/main/java/com/redhat/che/keycloak/server/KeycloakHttpJsonRequestFactory.java) which is bound for the rh-che distribution. 

Two approaches I was considering was detecting that the source of the requests is internal, or alternatively, setting passing the service account token as a header and using that to confirm it came internally.

**Comment by ibuziuk** [comment]
@amisevsk thanks for clarifications, using service account token looks like a valid solution

**Comment by ibuziuk** [comment]
PR is pushed to master
