### ISSUE TITLE
Need to pre-pull images required for  'java-maven' Che 7 devfile used on che.openshift.io and compare workspace startup time with non-prepulled devfiles

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1428]
Potential candidates from e2e happy path - https://github.com/eclipse/che/issues/12728
I believe this list needs to be reconsidered and updated:

- eclipse/che-jwtproxy:latest
- quay.io/eclipse/che-java11-maven:nightly
- eclipse/che-machine-exec:7.0.0
- eclipse/che-theia:7.0.0
- eclipse/che-remote-plugin-runner-java8:7.0.0

**Comment by amisevsk** [comment]
If we mean pre-pull via k8s image puller, we'd need some work on that side. Currently there's a limit to how many images it can work on (`5Mi` per container, per node).

**Comment by ibuziuk** [comment]
@l0rd looks like we have no capacity for this task in the next sprint. Are you ok if we will work on it after GA release (according to the metrics workspace startup is relatively fast atm, so optimization is not crucial atm)

**Comment by skabashnyuk** [comment]
> Currently there's a limit to how many images it can work on (5Mi per container, per node).

What does it mean 5Mi?

**Comment by l0rd** [comment]
@ibuziuk I am ok with postponing that

**Comment by amisevsk** [comment]
>What does it mean 5Mi?

The minimum memory request/limit for kubernetes containers is 5 Mebibytes. Since the containers started by a daemonset belong to a single namespace, this can cause problems. E.g. `5Mi` per container, times 5 containers in the daemonset, times 75 nodes in the cluster = `1875Mi` quota used on that namespace. Each additional container we'd want to add would increase the request by `375Mi`. 

The solution to this would likely be grouping containers into daemonsets that will fit and removing them once they are ready. As long as the daemonsets are started frequently enough the images should always be cached [1].

The other thing that would need investigation is how many images can be stored in the cache; if caching the 21st image means dropping the 1st, then we would have to think about prioritization.

[1] - This is probably a good idea to implement regardless, since without manual intervention I don't think a daemonset will rollout new images when they are pushed.

**Comment by aditya-konarde** [comment]
I've added a parameter to the template so that we can control replicas of this pod in different environments

- https://github.com/redhat-developer/kubernetes-image-puller/pull/10
- https://github.com/openshiftio/saas-openshiftio/pull/1317

**Comment by ibuziuk** [comment]
blocked by https://github.com/redhat-developer/rh-che/issues/1549

**Comment by amisevsk** [comment]
PR updating devfiles to be cached has been merged. The current list is
```
eclipse/che-jwtproxy:latest
quay.io/eclipse/che-java11-maven:nightly
eclipse/che-machine-exec:7.0.0
eclipse/che-theia:7.0.0
eclipse/che-remote-plugin-runner-java8:7.0.0
```
The image puller is currently only running on prod-preview and caching images in cluster 2a (and is still out of date since we need to rollout a new deployment). Since these images are used for Che 7.0.0 workspaces, we likely need to wait for 7.0.0 rollout to get meaningful data from production.

**Comment by ibuziuk** [comment]
@amisevsk since prod has been updated could we close this issue now (e.g. for analyzing the data between pre-pulled & non-pre-pulled devfiles)?

**Comment by ibuziuk** [comment]
makes sense let's add it to the next sprint and do comparison once Che 7 is updated to GA

**Comment by amisevsk** [comment]
The current plan for testing this is
1. Wait for 7.1.0 to roll out to production
2. Get timing data for starting a java-maven workspace
3. Update puller to cache images used in 7.1.0 workspaces (tagged 7.1.0)
4. Re-do timing tests with images cached

The only concern with this approach is if there are any shared layers between 7.0.0 and 7.1.0 images, we might show less of an effect than otherwise; there's no real way around this though, since we can't easily control the images used in workspaces (apart from the main container).

**Comment by amisevsk** [comment]
All done, email sent out to mailing lists.
