### ISSUE TITLE
Testing RH-Che update to Che7 GA

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#1607]
We need to verify that Che7 GA update works correctly on prod-preview

**Comment by ScrewTSW** [comment]
# .NET Core - WARN
- workspace startup works
- IDE loads
- **LSP not working correctly, even after `update dependencies` and `build` the syntax highlight** underlines syntax that's correct
- Commands:
  - `update dependencies` - OK
  - `build` - OK
  - `run` - OK
- deployment successful, application works as expected

# Apache Camel based on Spring Boot - WARN
- workspace startup works
- IDE loads
- LSP - **Takes very long time to start, is stuck at 57% for about 5 minuites**
- Commands:
  - `build the project` - OK
  - `run the services - OK
  - `8080/tcp` - OK - opens the deployment, API works, Swagger loads, but the API testing doesn't work
```
TypeError: NetworkError when attempting to fetch resource.
```
  - `run the services (debugging enabled)` - OK , port 5005 is exposed

# Django - FAIL
- worksapce startup works
- IDE loads
- Python LSP - **Stuck on `Refreshing Python Interpreters`** - FAIL
- Commands:
  - `install dependencies` - OK
  - `run server` - OK
  - `django` - **FAIL - opens the deployment successfully but `404` is given**
  - `migrate` - OK
```
Operations to perform:
  Apply all migrations: admin, articles, auth, authentication, contenttypes, profiles, sessions
Running migrations:
  No migrations to apply.
```
  - `run server in debug mode` - OK

# Go - OK
- workspace startup works
- IDE loads
- LSP - OK
- Commands:
  - `run current file` - OK
  - `run outyet` - OK
  - `stop outyet` - OK
  - `test outyet` - OK

# Java Gradle - OK
- workspace startup works
- IDE loads
- LSP - OK
- Commands:
  - `gradle build` - OK
  - `gradle run` - OK

# Java Maven - OK
- workspace startup works
- IDE loads
- LSP - OK
- Commands:
  - `maven build` - OK
  - `maven build and run` - OK

# Java Spring Boot - OK
- workspace startup works
- IDE loads
- LSP - OK
- Commands:
  - `maven build` - OK
  - `run webapp` - debug is enabled by default, OK
  - `8080/tcp` - OK

# Java Vert.x - 
- workspace startup works
- IDE loads
- LSP - OK
- Commands:
  - `maven build` - OK
  - `run app` - OK
  - `8080/tcp` - OK

**Comment by amisevsk** [comment]
A second pair of eyes:

- .NET Core:
  - LSP issues are known, I think they are related to https://github.com/eclipse/che/issues/13427. The LSP appears to work correctly after refreshing the page.
  - Highlights are weird (wrong area highlighted on syntax issue)

- Django:
  - LSP issues https://github.com/eclipse/che/issues/14074 is still open
    - Also, PR: https://github.com/eclipse/che-theia/pull/427
  - **Reproduced** `run server` issue; REST framework requires path `api` or `admin`
    - If you open the page in a new tab, the 404 page suggests this
  
- Java with Spring Boot and MySQL
  - Could not reproduce LSP issue but did not stress it very much
  - I did not get the errors when running the tasks, but I believe it is a known issue.

- NodeJS + MongoDB
  - Known issue with 404; the sample app is a backend REST service so it's nigh impossible to test with a browser

- NodeJS React
  - `install all required dependencies` hangs after it looks like it should be complete; completes ~15 seconds later
  - Could not reproduce `start the local server` issue (maybe above task hadn't completed?)

- PHP Laravel
  - The magic incantation of commands that makes it work:
    1. `install dependencies`
    4. `Copy the example env file...`
    2. `Generate a new application key`
    3. `Generate a new JWT authentication secret
    5. `Run the database migrations`
    6. `Start artisan web server`
    - Think of it as a fun puzzle
  - Port 8000 is not exposed in the devfile; the reason `Application is not available` appears it because it has to expose the route -- refreshing fixes the issue.
  - Known issue: https://github.com/eclipse/che/issues/14010
