### ISSUE TITLE
[Infra Issue] Workspace stuck in stopping state upon deletion

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#1637]
Once workspace starts getting stopped it's stuck in the stopping state for extended period of time.

![image](https://user-images.githubusercontent.com/16451875/66027461-3d6d2c80-e4fb-11e9-859a-11749d96e10f.png)
![image](https://user-images.githubusercontent.com/16451875/66027475-46f69480-e4fb-11e9-9adc-fb26af1cedcb.png)

**Comment by ScrewTSW** [comment]
happened today once at `1a` and previously on `1a` as well

**Comment by Katka92** [comment]
The workspace was stopping for too long again on 2 and was not deleted correctly. Happend 2x for 2a too, 2x on 1a, once on 1b .
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/1525/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/1317/consoleFull
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/1317/consoleFull

This job on 2a failed because stopping lasted too long but it deleted workspace correctly. 
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/1318/console

**Comment by Katka92** [comment]
Seen again 1x on cluster 2.

**Comment by Katka92** [comment]
Seen again on 1a https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/1398/console

**Comment by Katka92** [comment]
Not seen for a long time. Closing.
