### ISSUE TITLE
Broken links on the User Dashboard

### ISSUE THREAD

**Issue by abonas** [redhat-developer/rh-che#1711]
clicking on "learn more" is linked to
https://che.openshift.io/docs/what-are-workspaces.html
but then navigates to 404 on
https://www.eclipse.org/che/docs/what-are-workspaces.html

![Screenshot at 2019-11-26 15-09-43](https://user-images.githubusercontent.com/6277245/69704086-77be0900-10fb-11ea-951a-7c65fa292714.png)

**Comment by ibuziuk** [comment]
List of the broken links:
- `Workspaces` tab / "Learn More" - https://www.eclipse.org/che/docs/what-are-workspaces.html
- `Factories` tab / "Learn More" - https://www.eclipse.org/che/docs/factories-getting-started.html

**Comment by themr0c** [comment]
So what we need is:

1. add redirects in che-docs website
2. fix the app to point to the new URL

-  https://www.eclipse.org/che/docs/what-are-workspaces.html -> https://www.eclipse.org/che/docs/che-7/workspaces-overview/
- https://www.eclipse.org/che/docs/factories-getting-started.html -> https://www.eclipse.org/che/docs/che-7/configuring-a-workspace-using-a-devfile/ 
-  https://www.eclipse.org/che/docs/organizations.html ->  https://www.eclipse.org/che/docs/che-7/managing-users/ 

Additionnally we need to get managing-users from the attic: https://github.com/eclipse/che-docs/pull/1037 or https://github.com/eclipse/che-docs/pull/954

But we won't get the workspaces part from the attic because it was chosen not to advertise that concept anymore. I hear different opinions on that topic, please get a consensus first.

**Comment by ibuziuk** [comment]
@themr0c @rkratky sorry, I'm not following. What is the plan with fixing this issue? any action items required from Hosted Che team or the ball is on the docs team side to get all the fixes in place?

**Comment by rkratky** [comment]
@ibuziuk, redirects are now in place for all three links you listed.

**Comment by ibuziuk** [comment]
verified on Hosted Che. Closing
