### ISSUE TITLE
temporary/ephemeral storage is very limited and can not be controlled explicitly 

### ISSUE THREAD

**Issue by maxandersen** [redhat-developer/rh-che#1770]
import any gradlew based project like https://github.com/maxandersen/jbang and run ./gradlew and you run out of diskspace instantly and the workspace freezes.

Looks like you get just a few hundred MB which is very easy to fill up with a project having to download dependencies. in case of mvn and gradle wrapper that steals ~4-500 MB.

workaround is to enable persistent storage then it seems you get at least 1GB.

See https://github.com/eclipse/che/issues/15721

Also sometime workspaces are failing to start with 

![ephemeral](https://user-images.githubusercontent.com/1461122/56230975-a233e800-607d-11e9-8012-3076b34cc1ea.png)

**Comment by ibuziuk** [comment]
The interesting thread on openshift dev `How to set quota emptyDir on OpenShift 4.2`

**Comment by pdaverh** [comment]
Has the change to 2GB resolved this issue?

**Comment by ibuziuk** [comment]
@pdaverh this issue is about ephemeral storage which can not be controlled. For the toolchain running on OSD v4, it is expected that ephemeral storage will be explicitly controlled per-user - https://github.com/codeready-toolchain/host-operator/blob/master/deploy/templates/nstemplatetiers/basic/cluster.yaml#L15

**Comment by ibuziuk** [comment]
@alexeykazakov FYI ^

**Comment by ibuziuk** [comment]
Closing as outdated
