### ISSUE TITLE
Can not open workspace from Codebases view (ERR_TOO_MANY_REDIRECTS)

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#180]
The following error occurs when trying to open a workspace from "Codebases" view on openshift.io: 
```
This page isn’t working
sso.openshift.io redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS
```
Workaround: clearing cookies / incognito mode sometimes also helps

**Comment by alexeykazakov** [comment]
I see there is "response_mode=fragment" in HTTP request from Che to sso.openshift.io (Keycloak). Most likely it's from JavaScript Keycloak Adapter. I guess this forces Keycloak to use fragments (#) instead of URL parameters (?) in redirect URLs. Fragments can be handled by JavaScrtipt only. If Tomcat (Java) Adapter is involved here too then it won't handle fragments correctly.

**Comment by ibuziuk** [comment]
Might be related issue - https://github.com/fabric8-ui/fabric8-ui/issues/1539

**Comment by davidfestal** [comment]
let me try to explicitly disabling the `fragment` response mode in the dashboard code.

**Comment by alexeykazakov** [comment]
I actaully see problem only when response_mode=fragment is not used. In both cases Keycloak uses fragments (have no idea why) but it works only if response_mode=fragment
I guess because it's keycloak.js that sends requests with  response_mode=fragment 
but when it's not working the request comes from Tomcat Adapter or whatever is used by Che

**Comment by l0rd** [comment]
The fix for this has been deployed on OSIO (tenant version 1.0.208)
