### ISSUE TITLE
Testing che when OpenShift is loaded or overcommited

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#194]
See - https://issues.jboss.org/browse/CHE-248

**Comment by amisevsk** [comment]
Update on the status of this issue, from when I worked on it earlier:
- I was able to reproduce all of the issues described by @snjeza .
- The improvements to `JAVA_OPTS`, etc. by @l0rd make this issue far less likely to occur (you kind of have to try to make it happen -- just doing a large maven build will fail gracefully-ish)
- While oom detection is still not included (see first point of #198), `WsAgentStateController` does an alright job of detecting issues and notifying the user when an error *does* occur.
- Since we set the termination grace period on workspace pods to 0, we no longer have the issue where the "workspace is no longer responding" prompt fails to restart workspaces.
- Fixing / improving on the remaining issues is something that should probably wait for a more detailed SPI design around workspace health. We are still tied to Docker in detecting these issues, where I think some OS functionality could simplify the process for us

As a final note: one key issue here is that as it stands, all of the functionality around pod lifecycles provided by OpenShift are useless or unused for workspaces. Pod health issues are detected, but it happens too slowly for our purposes (since there is one pod per workspace, we need to know immediately if there is an issue), and since we have to inject agents into the workspace, the automatic restart that Openshift does results in a nonfunctioning workspace.

**Comment by ibuziuk** [comment]
@rhopp do we have dedicated upstream / functional test issue? I plan to close this issue in favour of one your team is working on

**Comment by ibuziuk** [comment]
@rhopp @ScrewTSW @Katka92 ^

**Comment by Katka92** [comment]
@ibuziuk There are performance tests implemented. The dockerfile was created to ease the usage of the tests [1]. There is a README [2] with information how to run them.

[1] https://github.com/redhat-developer/che-functional-tests/issues/449
[2] https://github.com/redhat-developer/rh-che/tree/master/load-tests

**Comment by ibuziuk** [comment]
Closing due to the initial implementation of https://github.com/redhat-developer/rh-che/tree/master/load-tests
