### ISSUE TITLE
Add Kubernetes LS

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/rh-che#213]
cc/ @jpinkney

**Comment by slemeur** [comment]
Hi @JPinkney.

Excellent work. I gave a look at the following [video](https://vimeo.com/230191488) this is very impressive!

I think we need to tweak the languages that is used in the Settings window:
![screen shot 2017-08-21 at 18 45 49](https://user-images.githubusercontent.com/1636769/29529716-13c6402a-86a1-11e7-9cd9-14d4fd8d8140.png)
On the left, the section indicates "YAML" under "Language Server Settings" and on the right area, you are mentioning only "Kubernetes and Kedge". It is a bit confusing: the settings allow to configure Kubernetes and Kedge schemas only? or it is possible to configure any kind of schema for yaml files? 

The way I'm understanding how the table is working is the following:
- User selects a schema and then defines to which files it applies to
If that's correct, we should probably be a little bit more specific to the user in the table header:
- Instead of "Url" --> "Schema Url"
- Instead of "Glob" --> what about "Apply To" 
- Similarly, the "Add URL" button could be renamed "Add Schema URL"

In the popup "Add URL" popup:
![screen shot 2017-08-21 at 19 04 17](https://user-images.githubusercontent.com/1636769/29530336-91eb4c46-86a3-11e7-90de-f4e2add0d1dd.png)
- Title of the popup should be "Add Schema URL"
- Popup could have a little text: "Add a new schema by providing its URL:"
- You could then remove the "URL" label before the textfield
- Finally, you could then rename "OK" primary button by "Add"

As a potential improvement for later:
- when the user is selecting a file, you could show a wizard to allow the user to select a file from the project tree or reuse the widget that is used in the "Navigate To File" feature.

**Comment by JPinkney** [comment]
Hi! Its possible to configure any schema file, I'll need to re-word that. It's more meant to say kedge and kubernetes are special keywords that make it so you don't have to manually enter the url for those. However, if you want any other schema file you'll have to enter the url. I'll make sure to make those adjustments!
