### ISSUE TITLE
Decrease resource quota limits on OSIO

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/rh-che#283]
Che namespaces in OSIO has the following [`ResourceQuota` specification](https://github.com/fabric8io/fabric8-online/blob/master/packages/fabric8-online-che-quotas-oso/src/main/fabric8/compute-resources-rq.yml#L8):

```json
    limits.cpu: "6"
    limits.memory: 3Gi
```

We should try to lower that to at least 2.5Gi and 5cpu. This issue is about:

- [x] Validate that we can build/run/debug spring boot and vertx quickstart on OSIO with lower limits.
- [x] [eventually] Optimize wsmaster and wsagent [`JAVA_OPTS`](https://github.com/fabric8io/fabric8-online/blob/master/apps/che/src/main/fabric8/cm.yml#L23) (c.f. [this article](https://developers.redhat.com/blog/2017/04/04/openjdk-and-containers/))

**Comment by l0rd** [comment]
@kbsingh I've created this issue after our discussion on that this morning and I would like to add it to next sprint

@gorkem As a scenario to validate that we can run Che with a given `ResourceQuota` I've specified:

> build/run/debug spring boot and vertx quickstart on OSIO

Do you think that's enough? Or do you have in mind a better scenario to test Che is working with low `ResourceQuota` limits?

**Comment by ibuziuk** [comment]
upstream Issue related to wsagent ` JAVA_OPTS` - https://github.com/eclipse/che/issues/4152#issuecomment-329284011

**Comment by ibuziuk** [comment]
Results of the first round of investigations:

![image](https://user-images.githubusercontent.com/1461122/30540846-14b34706-9c79-11e7-8471-47dc7cb58817.png)

I was able to run / debug spring-boot & vertx quikstarts on minishift with the following cpu / memory limits:

```
  spec:
    hard:
      limits.cpu: "5"
      limits.memory: 2.5Gi
```

There is also funny thing in rh-che devscripts with overriding default resource memory requests [1]
As one can see memory limit / request for workspace pod on minishift is sufficiently lower than what is used on prod cluster:

```
limit 1300 vs 2300
request 500 vs 1500
```
We briefly discussed this with @l0rd and it was decided that those limits are overridden accidentally (when memory was enlarged on osio we simply forgot to update it in our scripts. In general those memory env vars were overridden with the idea in mind of making memory properties configurable on minishift )  

So, on minishift the following limits / request are currently used for the che-server & workspace pods and it is possible to run / debug vertx spring-boot quickstarts:
**server**
```
    Limits:
      cpu:      1
      memory:   700Mi
    Requests:
      cpu:      60m
      memory:   256Mi
```
**workspace**
```
    Limits:
      cpu:      1
      memory:   1300Mi
    Requests:
      cpu:      60m
      memory:   500Mi
```
According to my minishift setup it is technically possible to run che-server / workspace with even 2Gi of RAM, but I just do not want to jump the gun with this statements. What about lowering limits to 2.5Gi for prod now and take a look how this would behave in the real life? In the mean time I would continue investigations on further optimizations.
@l0rd @kbsingh WDYT ?


[1] https://github.com/redhat-developer/rh-che/blob/master/dev-scripts/openshift_deploy.sh#L253

**Comment by l0rd** [comment]
@ibuziuk very good! Can you try with 2GB limit now? And please confirm that
on your minishift you really get OOM error when trying to use too much RAM
(e.g. building eclipse/che).

Another thing you may want to test before moving to prod (if you haven't
yet) is building/running/editing while Bayesian agent is running.

Il 18 set 2017 14:54, "Ilya Buziuk" <notifications@github.com> ha scritto:

**Comment by ibuziuk** [comment]
> And please confirm that on your minishift you really get OOM error when trying to use too much RAM
> (e.g. building eclipse/che).
I was not able to build che project even with 3GB quota, maven process is simply killed:
![image](https://user-images.githubusercontent.com/1461122/30554885-3eb2a34e-9ca6-11e7-82ab-144cc9902b69.png)


> Another thing you may want to test before moving to prod (if you haven't
> yet) is building/running/editing while Bayesian agent is running.
I was able to build / run / debug vertx spring-boot quickstarts with 2 GB of ram but I was not able to make bayesian work properly:

```
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-core</artifactId>
            <version>1.1.10</version>
        </dependency>
```
No, error are reported when the following dependency is added to pom.xml and there are no errors in che-server / ws-agent logs. 

Image that I used is `nightly-fabric8` form https://hub.docker.com/r/rhchestage/che-server/tags/

**Comment by ibuziuk** [comment]
Some extra notes:
In OpenShiftConnector `workspaces-memory-limit` / `workspaces-memory-request` cm values are used for workspace container creation (currently set to 2300Mi and 1500Mi respectively). At the same time there is another property `che-workspaces-java-opts` which is used for specifying options that will be used for running workspace agents (we do not specify `che.workspace.maven.options` so for maven the same options are used). `-XX:MaxRAM=1300m` in `che-workspaces-java-opts` limits memory usage to 1300Mi for workspace agents. But there is still extra 1G of RAM for the workspace container [2] (I guess when extra 1G was added `che-workspaces-java-opts` were not updated deliberately, so that this RAM would be used not by workspace agents, but for running the build and user app, because previously we have `workspaces-memory-limit` =  `-XX:MaxRAM` from che-workspaces-java-opts and this caused the situation when there were no free RAM to run the build). 

@l0rd vertx / spring-boot builds & app itself do not require a lot of RAM and 500 extra MB should be enough

```
Another thing you may want to test before moving to prod (if you haven't
yet) is building/running/editing while Bayesian agent is running.)
```
I was not able to make Bayesian working as described in the previous comment, but as I understand RAM that is used by Bayesian is part of `XX:MaxRAM=1300m` 

[1] https://github.com/fabric8-services/fabric8-tenant-che/blob/master/apps/che/src/main/fabric8/cm.yml#L24
[2] https://github.com/fabric8io/fabric8-online/pull/213

**Comment by gorkem** [comment]
Bayesian LSP is a node.js process so the memory used by bayesian LSP is not part of the Java process as defined by `XX:MaxRAM=1300m`

**Comment by ibuziuk** [comment]
@l0rd @gorkem still was not able to run bayesian on minishift (look like that for some reason node is not started). So, I wanted to measure how much RAM the node process consumes on osio. Using `pmap -d` it looks like the cost of running bayesian is ~ 90 Mb

`mapped: 1199020K    writeable/private: 88204K    shared: 0K                                                     
`

**Comment by ibuziuk** [comment]
More research notes
During the discussion it was decided that it should be possible to lower memory consumption that is used by che-server. After some testing it looks like the best we could do is to lower memory consumption only for 100Mb:

- with 400Mb che-server pod is failing to start
- with 500MB  pod is killed during workspace creation

![image](https://user-images.githubusercontent.com/1461122/30616214-d34d92e8-9d91-11e7-8c6e-c3d0c3d61adb.png)

with 600Mb I have not spot any sufficient differences in comparison with 700Mb. I have not played with GC options though (maybe using smth. else instead of Garbage First collector would improve the situation, but I would not count on it much)

Also, haven't tried to optimize ws-agent memory usage yet. According to `pmap -d` when workspace is started it uses ~1100Mb, so maybe it would be possible to take some memory from it (currently we are using `maxRAM=1300m` for it):

> mapped: 4539908K    writeable/private: 1063988K    shared: 3296K                                                                                                                                                           

So, the best combination of resources (600 for che-server / 1300 for wsagent / 600 everything else in the workspace like user app / mvn builds) I come up with by now is available in the following PR [1] and can be tested on osio (llast ink for tenant update is in the PR). I was able to create spring-boot & vertx workspaces build / run / debug / execute tests. However, when I tried to execute several operations simultaneously (debug vertx, run build from terminal and execute test for IDE) once I was able to hit memory limit and workspace container was killed for vertx quickstart:

![image](https://user-images.githubusercontent.com/1461122/30619609-9e196ea8-9da0-11e7-856e-f576b042b2c4.png)

Keep investigating..

[1] https://github.com/fabric8-services/fabric8-tenant-che/pull/29

**Comment by kbsingh** [comment]
great progress here guys!

Just one note - for the che-server component, I would not bother optimising it for rsource usage if Che-MT is close enough  ( and it does seem to be ).

**Comment by gorkem** [comment]
@ibuziuk What were the  -`XmaxRAM` value used when testing the lower che-server pod memory settings?

**Comment by ibuziuk** [comment]
@gorkem I always allocated all che-server pod memory to `XmaxRAM`

**Comment by ibuziuk** [comment]
More updates
It looks like wsagent is working quite stable with 1Gb of RAM  for **quickstarts** - was able to run / build / debug / execute tests not only for vertx / spring-boot quick starts but also for relatively small but real projects like 'che-starter' (also run several actions simultaneousy e.g. run & build & test + get Bayesian warnings). But, decreasing RAM in ws-agent would dramatically affect the range of the project that could be used in osio, e.g. small projects would work fine with 1GB and even less, but if one would try to work with smth. more sufficient  1GB is definitely not enough for maven plugin, AST resolution etc.

Important note that I got from @eivantsov that che by default is using 2Gb for ws-agent because there were situations when it was crashing with 1.5Gb (but this really depends on the project)

Also, technically it is possible to have quickstarts running with quota of 2Gb (600 for server, 1100 for ws-agent, 300 for the rest) but this would kill workspace pod when several operations would be executed simultaneously. 

So, shrinking workspace resources would definitely affect what user would be able to do with Che on osio, but after some testing of quickstarts I would propose allocate 2.5Gb in the following proportion (600 server / 1200 ws-agent /  700 everything else in workspace like bayesian, build, user app etc)

PR - https://github.com/fabric8-services/fabric8-tenant-che/pull/29/

@l0rd @kbsingh @gorkem WDYT ?

**Comment by kbsingh** [comment]
@ibuziuk +1 from me, this works for now. 
We can then align with 2GB for che overall once che-server moves out ( to che-MT ).

**Comment by ibuziuk** [comment]
@ldimaggi this change [1] is pretty crucial, so it would be really great to get QA approval before merging (che tenant can be updated using the last link [2] in PR). Basically, end-user should not spot any differences from usability perspective with new quotas.

![image](https://user-images.githubusercontent.com/1461122/30658478-0c00b0ee-9e3b-11e7-99d1-9753d9a28ece.png)

Will you be able to review & approve ?

[1] fabric8-services/fabric8-tenant-che#29
[2] https://openshift.io/_profile/_tenant?cheVersion=PR-v8fa786e-12&mavenRepo=https://nexus.cd.test.fabric8.io/content/repositories/staging

**Comment by ibuziuk** [comment]
Closing. PR has been merged. Feel free to reopen if there would be some quota related problems
