### ISSUE TITLE
Error when starting agent

### ISSUE THREAD

**Issue by jgallucci32** [redhat-developer/rh-che#331]
When creating a new workspace using any of the available stacks I get the following error:
```
Unable to start workspace agent. Error when trying to start the workspace agent: Start of environment 'default' failed. Error: Agent com.redhat.bayesian.lsp not found
```
The Che Server is started using  `run_che.sh` on RHEL 7.4 with Docker Version 1.13.1, build 4df6abf installed from the RHEL7 Extras repository.

**Comment by ibuziuk** [comment]
it looks like 'run_che.sh` script is using obsolete (5 month old) `rhche/che-server:nightly` image. As a workaround one can try updating image manually in the script [1] with one of the latest images from Dockerhub [2]. Basically, we do not use nightly anymore, so need to modify script, so that it would take image to run as a parameter

[1] https://github.com/redhat-developer/rh-che/blob/master/run_che.sh#L16
[2] https://hub.docker.com/r/rhche/che-server/tags/

**Comment by l0rd** [comment]
@jgallucci32 To start Che on Docker you should use Che CLI https://www.eclipse.org/che/docs/setup/cli/index.html
