### ISSUE TITLE
Run As -> JUnit test works only if the project was built beforehand 

### ISSUE THREAD

**Issue by gorkem** [redhat-developer/rh-che#365]
**Issue problem:** 
When I right click on and invoke _Run JUnit Tests_ for a vertx booster project it executes and fails with `No test found to run.Test suite is empty.`. 

Upstream issue - https://github.com/eclipse/che/issues/6549

**Comment by ibuziuk** [comment]
@gorkem in order to run tests one should build the project first (agree, it is not very straight forward and probably we need to open an issue upstream). However, I got the following problem even after building booster project.

![image](https://user-images.githubusercontent.com/1461122/31113772-144b5116-a81b-11e7-8efa-c576666a8fae.png)

> 
> java.io.FileNotFoundException: target/classes/META-INF/fabric8/openshift.yml (No such file or directory)
> 	at java.io.FileInputStream.open0(Native Method)
> 	at java.io.FileInputStream.open(FileInputStream.java:195)
> 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
> 	at io.openshift.booster.test.OpenShiftTestAssistant.deploy(OpenShiftTestAssistant.java:68)
> 	at io.openshift.booster.test.OpenShiftTestAssistant.deployApplication(OpenShiftTestAssistant.java:82)
> 	at io.openshift.booster.OpenShiftIT.prepare(OpenShiftIT.java:25)

**Comment by ibuziuk** [comment]
There are two tests in vertx booster quickstart `HttpApplicationTest` & `OpenShiftIT`. Once the project is built the first one works just fine, but the `OpenShiftIT` fails with on prepare phase with:

```
target/classes/META-INF/fabric8/openshift.yml (No such file or directory)
java.io.FileNotFoundException: target/classes/META-INF/fabric8/openshift.yml (No such file or directory)
```
I believe this is expected since this fails in the same way locally when running from desktop IDE and the test itself is about deploying app on the cluster which requires additional configuration

**Comment by ibuziuk** [comment]
After reading through the vert.x docs[1] in order to run the `OpenShiftIT` it is expected that user will login to oc cluster and deploy the app via `$ mvn clean fabric8:deploy -Popenshift`. Once it is done `OpenShiftIT` test will be passing:

![image](https://user-images.githubusercontent.com/1461122/31116076-0dc9b1d4-a825-11e7-8b61-d1532a1640ff.png)

However, I do not think that this scenario is smth. that is supposed to be demoed with osio. Technically, it should be possible to deploy this app from che on osio to some other csuster and execute this test, but I'm not sure this is a osio use-case where deployments to stage / run is powered by jenkins pipelines

[1] https://appdev.openshift.io/docs/vertx-runtime.html#mission-http-api-vertx

**Comment by ibuziuk** [comment]
@benoitf hmm.. it looks like the problem with permissions is not fixed for spring stack. The 'build' command fails with the following error:

ERROR in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - openFile(/tmp/spring.log,true) call failed. java.io.FileNotFoundException: /tmp/spring.log (Permission denied)

wondering if this is coupled with the switch to devshift registry where for some reason obsolete images are used?

**Comment by benoitf** [comment]
@ibuziuk maybe it's because /tmp is missing here
https://github.com/redhat-developer/che-dockerfiles/blob/master/recipes/spring-boot/Dockerfile#L67-L76 ?

**Comment by ibuziuk** [comment]
but this is quite weird because we should have spotted this problem as part of PR[1] verification (which was applied more than 2 weeks ago) and switch to devshift registry happened last Friday


[1] https://github.com/redhat-developer/che-dockerfiles/pull/24

**Comment by ibuziuk** [comment]
Basically, currently all spring-boot tests are broken because of this problem and one should add `-DskipTests` to the build commands as a temp workaround

**Comment by benoitf** [comment]
@ibuziuk checking on how the images are pre-built, I saw that now the osio branch has been removed from the booster catalog
https://github.com/openshiftio/booster-catalog/issues/108

https://github.com/redhat-developer/che-dockerfiles/blob/master/recipes/spring-boot/init-maven.sh#L36

**Comment by ibuziuk** [comment]
yeah, looks like current build of docker images will be broken:
```
Step 14/16 : ADD https://api.github.com/repos/openshiftio/booster-catalog/git/refs/heads/osio /tmp/current-osio-sha1
Got HTTP status code >= 400: 404 Not Found
```
@benoitf but this does not explain this problem with tests, right (for already existing spring images build command should work fine) ?

**Comment by benoitf** [comment]
Maybe there were updates in the tests
BTW I fix issue there
https://github.com/redhat-developer/che-dockerfiles/pull/26

**Comment by ibuziuk** [comment]
The issue was fixed for GWT based IDE after switch to jdt.ls -https://github.com/openshiftio/openshift.io/issues/1060#issuecomment-443543046
