### ISSUE TITLE
Analytics error markers don't show after opening file (edit&save of the file is needed)

### ISSUE THREAD

**Issue by rhopp** [redhat-developer/rh-che#367]
**Issue problem:** 
Opening pom.xml with dependency with CVE does not show the error marker. It is shown only after some change has been made to the file and saved.
Screencast: https://youtu.be/qHegLIEI5II

rh che version: 2.0.35

version::Revision : fac865a74eebefc0Build Time : 2017-09-29 08:54:44

 - [ yes ] I can reproduce it on latest official image

Have pom.xml with dependency with vulnerability. For example 
```
    <dependency>
      <groupId>commons-fileupload</groupId>
      <artifactId>commons-fileupload</artifactId>
      <version>1.3</version>
    </dependency>
```

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [x] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by ibuziuk** [comment]
@tsmaeder any ideas why initial pom validation does not happen on file -> open event ?

**Comment by l0rd** [comment]
We need to validate that this is a bayesian LS problem (not Che).

**Comment by benoitf** [comment]
Also @msrb

**Comment by invincibleJai** [comment]
@ibuziuk @l0rd not sure but it looks related to https://github.com/eclipse/che/issues/5843
@tsmaeder can add.

**Comment by tsmaeder** [comment]
I was able to confirm that this has nothing to do with bayesian. If you introduce a xml syntax error (just add "asdf" somwhere, you get an indication of a parse error from the maven language server. When you close and reopen the file, you do not see an error at first, but only when doing a change in the file.
Debugging the workspace agent shows that the "textDocument/didOpen" handler is never invoked in TextDocumentService. The network log in the Chrome developer tools seems to indicate that the message has been sent, tough.

**Comment by tsmaeder** [comment]
I was able to confirm that this has nothing to do with bayesian. If you introduce a xml syntax error (just add "asdf" somwhere, you get an indication of a parse error from the maven language server. When you close and reopen the file, you do not see an error at first, but only when doing a change in the file.
Debugging the workspace agent shows that the "textDocument/didOpen" handler is never invoked in TextDocumentService. The network log in the Chrome developer tools seems to indicate that the message has been sent, tough.

**Comment by tsmaeder** [comment]
Could not reproduce in minishift.

**Comment by tsmaeder** [comment]
I think I know what is going on here: When opening a pom.xml file, I noticed the following error in the browser console:
```
Error: Cycle: text/plain
    at ContentTypeRegistry.isExtensionOf (built-codeEdit-amd.js:8426)
    at ContentTypeRegistry.isSomeExtensionOf (built-codeEdit-amd.js:8441)
    at Dispatcher._wireServiceReference (built-codeEdit-amd.js:38407)
    at Dispatcher.updateListeners (built-codeEdit-amd.js:38398)
    at Dispatcher.<anonymous> (built-codeEdit-amd.js:38378)
    at built-codeEdit-amd.js:1203
    at Array.forEach (<anonymous>)
    at EventTarget.dispatchEvent (built-codeEdit-amd.js:1200)
    at InputManager._setInputContents (built-codeEdit-amd.js:18539)
    at InputManager.<anonymous> (built-codeEdit-amd.js:18069)
    at settleDeferred (built-codeEdit-amd.js:4628)
    at notify (built-codeEdit-amd.js:4702)
    at MutationObserver.run (built-codeEdit-amd.js:4586)
```
Turns out the orion complains that there is a content type registered called "text/plain" that extends "text/plain". Turns out that BayesianLanguageServerModule does 
```
    description.setMimeType("text/plain");
```
and LanguageServerFileTypeRegister does a 
```
                    contentType.setExtends("text/plain");
```
I suspect the exception prevents the "didOpen" notification from being sent to the bayesian language server. If I am correct, this should be easy to reproduce locally by registering any given language server for "text/plain".

**Comment by tsmaeder** [comment]
I was able to reproduce the stack trace, but not the failure to send "didOpen" by registering a text/plain. Not sure yet it isn't related, though.

**Comment by tsmaeder** [comment]
I am out of ideas on this one: The developer tools in Chromium indicate that a "textDocument/didOpen" message has been sent over the same websocket as other message ("languageServer/initialize", for example). However, a breakpoint in BasicWebSocketEndpoint#onMessage() never receives this message.

**Comment by tsmaeder** [comment]
@sunix has suggested the request might be blocked in https://github.com/redhat-developer/rh-che/blob/master/plugins/keycloak-plugin-server/src/main/java/com/redhat/che/keycloak/server/KeycloakAuthenticationFilter.java#L136

**Comment by tsmaeder** [comment]
Nope, putting a breakpoint in KeycloakAuthenticationFilter shows that no websocket messages are getting filtered.

**Comment by sunix** [comment]
OK I can see a difference in behaviours between a Che running inside the local minishift and the one running in Openshift.io

Seems that in openshift.io, a new websocket channel is being recreated each time we reopen the file

In minishift, when closing and reopening pom.xml several times
![selection_071](https://user-images.githubusercontent.com/650571/31948112-43557cfe-b8d6-11e7-9318-136beef4103b.png)

In openshift.io, when closing and reopening pom.xml several times
![selection_072](https://user-images.githubusercontent.com/650571/31948154-666bd170-b8d6-11e7-80fb-553c22fbbec8.png)

**Comment by sunix** [comment]
Can reproduce now on minishift: seems that if the file is too big ( > 140 lines approximatively) we have the issue

**Comment by sunix** [comment]
This seems to be fixed in 5.19.0
I could reproduce with the minishift addon on 5.18.0: 
Having that the current minishift addon use Che 5.19.0
- Installing the che minishift addon https://github.com/minishift/minishift-addons/tree/master/add-ons/che
- in ~/.minishift/addons/che/streams/che-server-streams.json replace all occurence of 5.19.0 to 5.18.0
- apply the addons
 
        minishift addons apply anyuid
        minishift addons apply che

- go to the che dashboard (url provided)
- create a php workspace with a php project
- open index.php
- add many lines
- add errors: markers should appear
- close and reopen index.php
- the markers don't show up: we did reproduce it

![selection_074](https://user-images.githubusercontent.com/650571/32491737-1156ab82-c3b8-11e7-9a9a-7e1eda4ec1c4.png)

Removing the addon, reset the image-stream to 5.19.0 and try the same steps: can not reproduce
![selection_076](https://user-images.githubusercontent.com/650571/32491798-4e4c1d2e-c3b8-11e7-994f-286a13930d30.png)

**Comment by ibuziuk** [comment]
@rhopp could you please verify on osio ?

**Comment by rhopp** [comment]
Automated test [1] is passing against latest single tenant che on prod. I also tried it manually. Closing.

[1] - https://github.com/redhat-developer/che-functional-tests/blob/master/tests/src/test/java/redhat/che/functional/tests/AnalyticsErrorMarkersTestCase.java
