### ISSUE TITLE
Functional tests for multi-tenant che-server

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#447]
Need to cover multi-tenant che & canary rollout with che-functional-tests [1]. 

- run PR verification against prod-preview (che starter is not exposing route on prod)
- use prod-preview che-starter[2] route in order to test multi-tenant che-server (unleash toggle will not work against local che-starter - it must be deployed on the same cluster with unleash);

[1] https://github.com/redhat-developer/che-functional-tests
[2] http://che-starter-dsaas-preview.b6ff.rh-idev.openshiftapps.com/swagger-ui.html

**Comment by ibuziuk** [comment]
cc: @rhopp @Katka92 @ldimaggi

**Comment by rhopp** [comment]
We were thinking about this and now we're not sure we would be able to run PR check against multitenant che. Because with singe tenant we just edited deployment config of che-server in oso to use currently built rh-che image. This approach won't work with multitenant che. Even if we had rights to edit DC's on rh-idev it would affect every user of prod-preview which is not desired state.
If you have any ideas how to solve this, you are more than welcome to share them ;-)

**Comment by ibuziuk** [comment]
@rhopp it looks like we will need to have mt-che server on some test cluster like glusterpoc37aws.devshift.net / dev.rdu2c.fabric8.io:8443 and run the PR verification against it

@l0rd WDYT ?

**Comment by l0rd** [comment]
@ibuziuk @rhopp yes another test cluster (maybe freeint, in distinct project then the workspaces, may work too?) or deploying a second che server on rh-idev...Anyway we should involve service delivery team in the discussion.

**Comment by ibuziuk** [comment]
@vpavlin @jfchevrette could you recommend the preferred way for of hosting test mt che-server? 
- prod-preview / free-int (deploy che-server in distinct project then the workspaces)
- separate test che-server on dedicated (prod-preview only)
- dev.rdu2c.fabric8.io:8443 / glusterpoc37aws.devshift.net

**Comment by garagatyi** [comment]
Looks like this issue is not actual anymore. @ibuziuk WDYT?

**Comment by rhopp** [comment]
Agree this is not actual anymore. Closing.
