### ISSUE TITLE
Tuning workspaces JAVA_OPTIONS

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/rh-che#451]
openshift.io issue - https://github.com/openshiftio/openshift.io/issues/1411
That's about [this issue](https://github.com/openshiftio/openshift.io/issues/1411) and looking if these PRs (https://github.com/redhat-developer/che-dockerfiles/pull/28 https://github.com/fabric8-services/fabric8-tenant-che/pull/73) mitigate the problem or if we still need to fix `MavenServerMain`.

**Comment by jerboaa** [comment]
FWIW, I believe https://github.com/redhat-developer/che-dockerfiles/pull/28 is a work-around for https://github.com/openshiftio/openshift.io/issues/1411.

**Comment by jerboaa** [comment]
The reason why https://github.com/redhat-developer/che-dockerfiles/pull/28 is not sufficient is because `createExecutor()`[[1](https://github.com/eclipse/che/blob/master/plugins/plugin-maven/che-plugin-maven-server/src/main/java/org/eclipse/che/plugin/maven/server/MavenServerManager.java#L87)] is using `CommandLine.createProcess()` which in turn [clears the environment](https://github.com/eclipse/che/blob/master/core/commons/che-core-commons-lang/src/main/java/org/eclipse/che/commons/lang/execution/CommandLine.java#L101) before it spawns the process. Thus, `_JAVA_OPTIONS` is ineffective.

**Comment by skabashnyuk** [comment]
@jerboaa  would it be enough if we set here [1] JAVA_OPTS of caller process?

**Comment by jerboaa** [comment]
@skabashnyuk "here" is where exactly? In `createExecutor()`? It would be an improvement.

I'm not exactly sure what the calling process is, but if it's the che-workspace agent, then this should work. Ideally there would be one environment variable per process: One, `JAVA_OPTS` for the workspace agent, one `CHE_MAVEN_SERVER_OPTS`, say, for the maven server. It would avoid the issue of "not one set of flags fits for all che workspaces' Java processes" issue. For example if there was a `CHE_MAVEN_SERVER_OPTS` environment one could set `MaxRAM` for it as a slice of the total container limit.

**Comment by skabashnyuk** [comment]
https://github.com/eclipse/che/blob/master/plugins/plugin-maven/che-plugin-maven-server/src/main/java/org/eclipse/che/plugin/maven/server/MavenServerManager.java#L219

**Comment by l0rd** [comment]
The java_opts in this PR may be outdated with respect to the one set on upstream Che. When evaluating these we should have a look at upstream java_opts.
