### ISSUE TITLE
Run Che terminal in a sidecar container (Docker infra)

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/rh-che#539]
The idea is that we should [attach xtermjs to the runtime container](https://xtermjs.org/docs/api/addons/attach/) instead of executing it inside the runtime container itself. The implementation should provide support for Docker infra only. Kubernetes and Openshift should be supported as a second iteration.

**Comment by l0rd** [comment]
cc @AndrienkoAleksandr @ashumilova @eivantsov

**Comment by garagatyi** [comment]
We can probably use a tiny binary file that can communicate in an infrastructure-specific way with other containers of runtime. 
On OS/k8s it can use injected user token to access OS API to exec into the target container.
On Docker it is trickier since it doesn't have fine permissions model. So container with this agent would communicate with Docker API and be kinda privileged. Not sure whether this approach is secure enough for Docker or not. 

Additional thing to think about is that such an agent on OS would use centralized OS API node to send traffic of exec and user can influence stability of OS API by running `while true; do echo "DOS the API! ; done"`. Which seems a significant vulnerability.

**Comment by eivantsov** [comment]
We already run Che server container that has access to Docker API. Not sure I can say if or not it's secure.

As to bringing OpenShift down by doing verbose execs, this is how things look now and theoretically I can run such loops in OpenShift console terminal windows to pods. Never tried it though :)

**Comment by garagatyi** [comment]
@eivantsov 
> We already run Che server container that has access to Docker API. Not sure I can say if or not it's secure.

can you elaborate on what containers of a workspace have access to Docker API?

> As to bringing OpenShift down by doing verbose execs, this is how things look now and theoretically I can run such loops in OpenShift console terminal windows to pods. Never tried it though :)

Yeah, good point. But you don't call development stuff in those terminals, so it is safer for me. For development commands, it is very probable to run a command that generates a huge amount of output. 
BTW is there anyone whom we can ping to check whether it is a stability issue for OS and if so whether it is known and prioritized one. @l0rd

**Comment by eivantsov** [comment]
> can you elaborate on what containers of a workspace have access to Docker API?

We don't and won't have such containers. I am talking about Che server container, hinting that if we have one such privileged container in Che infra, running an additional one to handle terminal and execs won't jeopardize the host.

**Comment by garagatyi** [comment]
Oh, I see. I thought we considered one terminal container per workspace and inside of user runtime.

**Comment by garagatyi** [comment]
This is already implemented in upstream. Closing the issue. Feel free to reopen if you think that we still need this issue.
