### ISSUE TITLE
Minishift development environment setup for running rh-che multi-user locally

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#540]
Need to have a possibility to run multi-user rh-che locally on minishift. This would require to 

- [ ] mock fabric8-auth 
- [ ] mock fabric8-wit (api user service) 
- [ ] mock oso proxy
- [ ] create workspaces on minishift when running locally
- [ ] document rh-che multi-user local minishift setup

Once https://github.com/redhat-developer/rh-che/issues/532 is resolved it would not be possible to deploy multi-user rh-che to dev cluster and create workspaces against prod-preview oso cluster. Basically, with removing edit right we introduce hard dependency to fabric8-auth / oso proxy components. Need to come up with approach of testing rh-che locally or on dev cluster before merging PRs to master.

**Comment by l0rd** [comment]
This issue is blocking #489

**Comment by l0rd** [comment]
Some thoughts during sprint planning:
- For fabric8-auth mock: adding the code for the mock in fabric8-auth github repository
- For the proxy: maybe the proxy mock is not needed and we could use the openshift endpoint instead and using a dev flag for the token to use

**Comment by davidfestal** [comment]
So PR https://github.com/redhat-developer/rh-che/pull/711 fixes this issue in a way that is different of the initial issue description. Finally there's no need for any mock of fabric8 services.

Here is a short description of the proposed solution:
1. RhChe uses the Keycloak directly (as does upstream Che) instead of the `fabric8_auth` OIDC provider (this is mainly a yaml config change)
2. We use a `standalone` property in RhChe, that will be set to `true` when running it on Minishift by the minishift addon
3. When the `standalone` property is set to `true`, the RhChe Java implementation provides a Kubernetes client that points to the current cluster / namespace with the `rhche` service account instead of pointing the the OSIO user cluster / namespace with the fabric8 proxy service account.
4. In order to keep the feature that logs in the `oc` client with user OpenShift token at workspace start, the minishift account is linked to the user Keycloak account using a Keycloak Openshift identity provider.
5. Additionally, in order to avoid the need for the user to explicitly link his minishift account to his main Che Keycloak account, we switch the Keycloak autentication to use the Openshift identity provider. This way, when the user first logs into the Che server, he logs with his minishift account and the minishift and keycloak account are linked automatically. Later, when he stars a workspace, and types the `oc project` command in a terminal, he's directly connected to the default `myproject` project available in minishift by default. This provides a behavior very similar with what exists under OSIO.
6. Finally, the allowed web origins and redirect urls in Keycloak are modified because by default they contain the `che` prefix (service name) and here we use `rhche`.

The points 4 to 6 are applied by the [`keycloak_configurator`](https://github.com/redhat-developer/rh-che/blob/ccf4b83d1fd11a5aa44e6e1ed82124b86128b6af/openshift/minishift-addons/rhche-prerequisites/keycloak-configurator/source/keycloak_configurator/run.ceylon) command-line application that is run as an OpenShift Job when the Keycloak server is applied / started in Minishift by the Minishift addon.
