### ISSUE TITLE
Improve user experience when running multi user Che on OSO Pro

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/rh-che#542]
Following the doc to install multi user Che on OSO Pro may lead to Che not working properly.

- [x] We should test it to find eventual bugs
- [x] We should find a solution for the tokens that may expires (i.e. create the Che service account along with Che during deployment)
- [ ] ~~Add documentation for single user Che with Keycloak~~ will track that on an upstream issue
- [ ] ~~Check if a user is trying to create a multi container workspace with 2 services that have the same name~~  opened eclipse/che#8960

**Comment by l0rd** [comment]
Building postgresql image on OSO Pro fails. Here are the logs:
https://gist.github.com/jorgemoralespou/67ccfe783e9a8c7330425a4d3f829bf7

@davidfestal do you have an idea of what's happening? On minishift the same build work just fine.

**Comment by davidfestal** [comment]
@l0rd looking into the logs it seems the postgres image used is not the same: one is 

Successful:

```
Creating a new S2I builder with config: "Builder Name:\t\t\tPostgreSQL 9.5\nBuilder Image:\t\t\tcentos/postgresql-95-centos7@sha256:a914254fb38c4d76a95d1472081b04e998bb8d234b6000ce227bf7b21130e64e
```

Failing:
```
Creating a new S2I builder with config: "Builder Name:\t\t\tPostgreSQL 9.5\nBuilder Image:\t\t\tregistry.access.redhat.com/rhscl/postgresql-95-rhel7@sha256:d8b932fab1c9eb48a8a2f2fd94caf6dcff18a78413f621c92d280b158754d7ed
```

**Comment by garagatyi** [comment]
@l0rd about the case with SA instead of a token. Is there a requirement to execute all the operations with OS entities as a user or it is OK to do operations as an admin?

**Comment by eivantsov** [comment]
@davidfestal I can reproduce this issue with `rh-us-east-1.openshift.com`

```
Pulling image "docker-registry.default.svc:5000/eclipse-che/che-init@sha256:270a4afda5aa00c7fdecb28ab83b75707fc9a11b225994d264d85e2bdf262c76" ...
--
  | Pulling image "centos/postgresql-96-centos7@sha256:822dadfa60baf3109cc7243acb9bc02091ac53668b5f4a5b580506b257262965" ...
  | ERROR: Error writing header for "scripts": io: read/write on closed pipe
  | ERROR: Error writing tar: io: read/write on closed pipe
  | error: build error: Error response from daemon: {"message":"create 25cc70bec79ef47e1d160604c38a7d70642ca28b85cbb656dc6c6a705437384f: mkdir /var/lib/docker/volumes/25cc70bec79ef47e1d160604c38a7d70642ca28b85cbb656dc6c6a705437384f: permission denied"}

```

**Comment by ibuziuk** [comment]
> We should test it to find eventual bugs

Was able to deploy multi-user che on oso Pro following che 6 docs [1] and did some quick tests for workspace creation. Seems to work fine OOTB (s2i is not used anymore for db deployment)

> We should find a solution for the tokens that may expires (i.e. create the Che service account along with Che during deployment) 

sa token is already used by default for oso deployment. However, all workspaces must be created in the same namespace where che-server is deployed (sa token has rights only inside the namespace). More details in the docs [1]

> Add documentation for single user Che with Keycloak

The motivation behind this requirement is making che-host url not publicly available for single-user usecase. However, `single user Che with Keycloak` = `multi-user Che with Keycloak where there is only one user registered'. e.g. if user wants to have che-host secured by keycloak he will need to deploy multi-user che and have only one user registered for his account. Probably, we just need to clarify this point in the docs.

> Check if a user is trying to create a multi container workspace with 2 services that have the same name

I think we just need to create an upstream issue for handling this error  for `openshift` recipe type.  

Also, there are some things that also need to be documented IMO:
- how to deploy multi-user che to oso and point to existing keycloak instead of using default one ?
- how to allow workspace creation in new namespaces instead of reusing the one where che-server is deloyed ? (there would still be a problem with token expiration)

@garagatyi @davidfestal @l0rd WDYT ?

[1] https://www.eclipse.org/che/docs/6/che/docs/openshift-multi-user.html#openshift-online

**Comment by l0rd** [comment]
Ok to create an upstream issue for handling the error about 2 services with the same name

And then I think we can close this issue

**Comment by ibuziuk** [comment]
ok, will create one. What about docs ?  single user Che with Keycloak / how to deploy multi-user che to oso and point to existing keycloak instead of using the default one  / how to allow workspace creation in new namespaces instead of reusing the one where che-server is deloyed ?

**Comment by l0rd** [comment]
I would say:
- doc for single user che on oso (aka not secured che) -> *no*
- doc for deployment with existing keycloak -> *yes*
- doc to run ws in distinct namespace -> *no*

@slemeur what do you think?

**Comment by slemeur** [comment]
+1 
- We could have a mention about why we do not recommend to deploy Che single-user on OSO
- I don't think running ws in distinct namespace with OSO is necessary for the time being. We would better recommend OSD in this situation.

**Comment by eivantsov** [comment]
Docs cover how to deploy using existing Keycloak. And how to configure namespace policy for ws objects

**Comment by ibuziuk** [comment]
@eivantsov thanks for the pointer - was able to find the doc about using existing keycloak [1]. However, I was not able to find relevant info about workspace nemespace policy. There is a documentation for defining `CHE_INFRA_OPENSHIFT_PROJECT` so that workspaces would be created in the same namespace as che server. However, I think there should be also instructions for:
- creating workspaces in new namespace (not defining `CHE_INFRA_OPENSHIFT_PROJECT`. Doing it that way workspace would be created in new namespace with `name = workspaceId` )
- and probably creating all workspaces in particular namespace but not the same where che server is deployed.
 
[1] https://www.eclipse.org/che/docs/6/che/docs/openshift-multi-user.html#openshift-online

**Comment by ibuziuk** [comment]
Issue for recipe / service name validation https://github.com/eclipse/che/issues/8960
