### ISSUE TITLE
Che 6: preview url is not rendered correctly for vertx booster

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#569]
**Issue problem:** 
![preview_url](https://user-images.githubusercontent.com/1461122/37030017-a83adabc-2139-11e8-9313-04292e5f697d.png)

**Red Hat Che version:** 
reproduced against prod-preview che 6 https://rhche.prod-preview.openshift.io

version: (help/about menu)

 - [x] I can reproduce it on latest official image

**Reproduction Steps:**
Create workspace against vert.x stacexek with vertx http booster imported and execute run command.
ERROR: preview url is rendered as `http://${server.port.8080}`

Describe how to reproduce the problem

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [x] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by garagatyi** [comment]
The reason is that previewUrl has changed its format in Che6 and stacks in rh-che weren't updated properly

**Comment by garagatyi** [comment]
I can take a look and fix it

**Comment by garagatyi** [comment]
BTW there are no servers in stacks.json file at all. So preview URLs would not work in any case in my opinion.

**Comment by benoitf** [comment]
is that existing workspaces need to be migrated as well to include this server definition ? or only new workspaces

**Comment by garagatyi** [comment]
I think both

**Comment by garagatyi** [comment]
I fixed preview URLs and ports publishing in new workspaces. 
@l0rd do you think we should add a migration to fix it in existing workspaces?

**Comment by l0rd** [comment]
@garagatyi Che 6 is not in prod yet so I guess that there is no workspace to migrate (and we don't need to migrate prod-preview workspaces).

**Comment by garagatyi** [comment]
I mean migration of existing workspaces from Che5 to Che6 on prod. @davidfestal can you point me to a place where stacks are migrated?

**Comment by l0rd** [comment]
@garagatyi so you are saying that the preview links of an existing Che 5 workspace (a link that worked fine with Che 5) won't work anymore when the workspace is migrated to Che 6?

Anyway the Che migration service repo is [here](https://github.com/fabric8-services/fabric8-tenant-che-migration)

**Comment by davidfestal** [comment]
> Anyway the Che migration service repo is here

But the repo is not up-to-date currently. I'll push on a branch today so that @garagatyi can have a look.
OTOH, what I propose is that we _**open a separate issue**_ with all the additional required changes to apply to the workspace json during the Che 6 migration.
Then I'll be able to setup the appropriate mechanism to support them all.

**Comment by garagatyi** [comment]
@l0rd yes, we need to migrate workspaces configs from Che5.

@davidfestal Please let me know when the repo is updated. 

@l0rd WDYT about a separate issue for migration details suggested by David?

**Comment by l0rd** [comment]
@garagatyi +1 for separate issue with lower priority. We are not in GA, we are not even sure if there will be one user that will face this problem. I believe that current users ( beta testers) create new workspaces more than restart new ones. 

We do migration of workspaces to be sure that users won't lose their data but it's more of an exercise for us rather than a true requirement.

**Comment by garagatyi** [comment]
@l0rd if so we completely skip migration and spend this time on the other stuff

**Comment by garagatyi** [comment]
I created an issue #579
