### ISSUE TITLE
Improve rh-dev/che-dockerfiles

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/rh-che#670]
- [x] Parse boosters versions instead of hardcode it
- [ ] ~~Add some tests to make sure that when the booster is run we do not download mvn dependencies (QE team is working on this one)~~ - redhat-developer/che-functional-tests#269
- [x] Avoid Dockerfiles duplication in rh-dev/che-dockerfiles repository

(related to https://github.com/openshiftio/openshift.io/issues/3336)

**Comment by l0rd** [comment]
We should retrieve boosters versions informations [here](https://github.com/fabric8-launcher/launcher-booster-catalog)

**Comment by l0rd** [comment]
The part `Add some tests to make sure that when the booster is run we do not download mvn dependencies` should be handled by QE team

**Comment by l0rd** [comment]
@rhopp yes. The test should verify that when building the booster we don't download the dependencies (e.g. the deps are pre-downloaded when building the docker image).

**Comment by amisevsk** [comment]
Opened PR [1] to address the parsing boosters version part

Note that instead of extracting boosters version from the repo, I'm using the catalog rest api directly [2]. There is also and endpoint for staging at [3] which is currently unused.

[1] - https://github.com/redhat-developer/che-dockerfiles/pull/37
[2] - https://forge.api.openshift.io/api/booster-catalog
[3] - https://forge.api.prod-preview.openshift.io/api/booster-catalog

**Comment by ibuziuk** [comment]
@amisevsk I believe 2 & 3 are now fixed and for 2 there is an issue created by @rhopp - redhat-developer/che-functional-tests#269
So, I believe we can close it now, right ?
