### ISSUE TITLE
Pull Request Workflow

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/rh-che#708]
PR workflow does not work on openshift.io, need to fix it

**Comment by ibuziuk** [comment]
@l0rd @gorkem  @slemeur @nickboldt  could you please clarify what exactly this issue is about? I thought that contributor plugin is broken on osio, but it seems to be working fine and I was able to send a PR [1] from che on osio. Maybe some particular use-case does not work ?

[1] https://github.com/ibuziuk/asdasaaaaaaaaaaaaaa/pull/1

**Comment by slemeur** [comment]
It does not work on my side.
Here is a recording of what's happening.

![kapture 2018-06-28 at 20 49 41](https://user-images.githubusercontent.com/1636769/42054504-d9265180-7b14-11e8-8cf8-5e697afc63b5.gif)

**Comment by ibuziuk** [comment]
@slemeur interesting. I can create PR for workspaces created from both codebases UI & dashboard [1].
It is most likely related to the fact that github token is injected by che-starter and once you create workspace from codebases UI it should be possible to create subsequent workspaces from the dashboard and use the contributor plugin for PRs. BTW, thanks for reporting https://github.com/redhat-developer/rh-che/issues/727 once this issue is resolved creating first workspace from codebases UI in order to use the contributor plugin will not be required

[1] https://github.com/che-samples/angular-patternfly-demo-app/pull/1

**Comment by slemeur** [comment]
Tested by creating a new workspace from the codebase UI first - and indeed it worked. 

Thanks for the investigation @ibuziuk

**Comment by ibuziuk** [comment]
Closing in favour of https://github.com/redhat-developer/rh-che/issues/727
