### ISSUE TITLE
update docs how to deploy rh-che to ocp

### ISSUE THREAD

**Issue by riuvshin** [redhat-developer/rh-che#758]
current doc https://github.com/redhat-developer/rh-che#deploy-to-openshift-container-platform does not work with local ocp cluster deployed with `oc cluster up`
It deploys only che master and fails because there is no KC and DB deployed.

That is needed in order to fix ci job [1] which checks rh-che with current master of upstream

1 https://ci.codenvycorp.com/job/rh-che-ci-master/

**Comment by davidfestal** [comment]
With the time, RhChe has become more and more coupled with OSIO (Fabric8) sibling services. Let's mention:
- the way its implements multi-user support: based on the OSIO users and OSIO-specific link between the user and its allocated OSIO namespace on a given cluster,
- the way it uses `fabric8_auth` as an alternate OIDC provider instead of the dedicated Keycloak.
- the way it relies on the `fabric8_oso_proxy` to secure the user Che namespace and restrict its usage from the user while allowing creating user workspaces in it.

This had made RhChe impossible to run on Minishift, but also on OCP, for the same reasons.
The Minishift case has been fixed by providing a Minishift addon that switches to a new *standalone* mode, in which RhChe doesn't need any external Fabric8 services anymore. However, this standalone mode contains limitations, one of which is that only one user is supported for now (since it's mainly for testing / development purposes).

For OCP, no alternate installation method / script has been provided until now to enable this sort of *standalone* mode. We could certainly do something similar to what has been done in the Minishift addon, but then the same limitations would apply. Now the question is: is it really useful ?

And as for the failing CI Job, is it really expected that we would run the integration tests on this RhChe installation, knowing that, in any case, it is not intended to be production-ready (since it's based on a SNAPSHOT upstream version). Isn't this CI Job mainly a way to detect earlier any build problem that might appear with upcoming upstream changes that would be incompatible with the current RhChe code ?

Based on that, I'm not sure it would be a problem to remove the integration tests from the CI job as a first step. This would allow this CI Job to succeed again. And if later we decide to enable deploying RhChe on OCP again, I assume it wouldn't be a problem to test only a subset of features compatible with the OCP deployment limitations.

**Comment by ibuziuk** [comment]
agree with @davidfestal  that we should disable the integration tests for the https://ci.codenvycorp.com/job/rh-che-ci-master/ . Basically, the idea is that the job would fail if there are some `build time` problems against new version of the upstream Che. If the build with unit tests is passing against new version of Che than we are ~90 % sure that it would work. Integration tests would be performed during the PR check job once we would send PR with the version update in rhche cc: @l0rd

**Comment by riuvshin** [comment]
agree, so I will keep only compilation check on this job.

**Comment by l0rd** [comment]
Ok to remove integration tests for now. It looks like the more appropriate solution.

@riuvshin can't we use [minishift with `generic` `vm-driver`](https://docs.openshift.org/latest/minishift/using/run-against-an-existing-machine.html) insteado of OCP in the integration tests?

**Comment by riuvshin** [comment]
I think we can try to do same as I did for k8s... run minikube with driver none in docker as dind, but I can't run this on CI slaves because these slaves are utilized for many different things so they are not supposed to spawn that kind of processes on the host.

**Comment by ibuziuk** [comment]
I do not think this is relevant anymore. Closing
