### ISSUE TITLE
 "InternalEnvironmentFactory is not configured for recipe type: 'compose' when trying to create multi-machine workspaces multi-machine workspaces

### ISSUE THREAD

**Issue by chetips** [redhat-developer/rh-che#779]
- Go to https://rhche.openshift.io/dashboard/#/create-workspace
- Select any multi-machine stack
- Click Create
I get "InternalEnvironmentFactory is not configured for recipe type: 'compose'"

**Comment by ibuziuk** [comment]
@eivantsov is going to help with this task as part of adding new stacks required for `Codenvy.io -> OSIO` transition

**Comment by garagatyi** [comment]
@ibuziuk we don't have compose support in place for the time being. Here is the issue https://github.com/redhat-developer/rh-che/issues/638

**Comment by ibuziuk** [comment]
@garagatyi yeah, I know. For now we just want to remove all compose based stack from rh-che predefined stacks. Also, it would be nice to add validation with `compose recipe is not supported` during custom stack creation until #638 would be fixed (but this part is optional IMO and might be tricky to implement since I am not sure how difficult would it be to override the upstream validation in rh-che)

**Comment by ibuziuk** [comment]
Closing since compose recipies have been removed from rh-che stacks and not available by default - https://github.com/redhat-developer/rh-che/pull/787
