### ISSUE TITLE
Invalid "Preview:" URL in Spring and Nodejs stacks with respective samples

### ISSUE THREAD

**Issue by scela** [redhat-developer/rh-che#820]
- Log in to OSIO
- Create a workspace either from Spring or nodejs stack
- Open the workspace and get into Che
- Create a sample project either web-java-spring or web-nodejs-simple respectively
- Build and run

Preview: ${server.9000/tcp} is shown rather than a real URL

**Comment by ibuziuk** [comment]
@rhopp thanks for detailed research. So, the main problem is inconsistency between our stacks & samples. I believe @eivantsov already consolidated [1] samples with stacks upstream and we need to do the very same thing for rhche.

Radim, will it be possible if QA team would work on https://github.com/redhat-developer/rh-che/issues/763 in the current sprint and provide relevant PRs for consolidation of our stacks with sample 
e.g. for fixing node.js it would require adding missing servers [2] to https://github.com/redhat-developer/rh-che/blob/master/assembly/fabric8-stacks/src/main/resources/stacks.json#L827 / for dotnet - renaming server [1] and updating command etc. Since stacks are already consolidated with samples upstream I imagine that this would be pretty straigh-forward to do. I imagine that since there are quite a few inconsistencies currently and most of them are pretty easy to fix, it would make sense if QA during checking rh-che stacks against samples would fix the problem on the spot and provide PR to rh-che with the fix ? WDYT  
I believe @eivantsov would be able to provide some guidance if smth. would be not clear 

[2] https://github.com/eclipse/che/commit/ad0ad4514398b3f20c2265193924f159de6560b0 
[1] https://github.com/eclipse/che/blob/master/ide/che-core-ide-stacks/src/main/resources/stacks.json#L1490-L1503
[3] https://github.com/eclipse/che/blob/master/ide/che-core-ide-stacks/src/main/resources/stacks.json#L626

**Comment by ibuziuk** [comment]
Should be closed once we update prod to Che 7 GA
