### ISSUE TITLE
Need to cleanup and make more uniform keycloak / fabric8-auth properties used in rh-che

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#836]
Issue is created as follow up of automatic Github linking PR - https://github.com/redhat-developer/rh-che/pull/810

>  In general I think an important issue in the near future is to make the properties we use more uniform -- we currently have e.g.
> ```
>   che-fabric8-user-service-endpoint: "https://api.prod-preview.openshift.io/api/user/services"
>   che-fabric8-auth-endpoint: "https://auth.prod-preview.openshift.io"
>   che-keycloak-auth-server-url: "NULL"
>   che-keycloak-realm: "NULL"
>   che-keycloak-client-id: "740650a2-9c44-4db5-b067-a3d1b2cd2d01"
>   che-keycloak-oidc-provider: "https://auth.prod-preview.openshift.io/api"
>   che-keycloak-js-adapter-url: "/_app/keycloak/RhCheKeycloak.js"
>   che-keycloak-use-nonce: "false"
> ```
> This is pretty confusing, as it's not clear which properties are important / which are used at all -- as an example, `che-keycloak-oidc-provider` caused me a lot of issues in working on this, as the docs suggest it can be used if `che-keycloak-auth-server-url` is `null`, but this is not the case. For now I think your approach may be the cleanest, so I'll go with that.
> 

[1] https://github.com/redhat-developer/rh-che/pull/810#issuecomment-415852628
[2] https://github.com/redhat-developer/rh-che/pull/810#issuecomment-416844666

**Comment by amisevsk** [comment]
@davidfestal Continuing the discussion from the PR, I see that the oidc provider and auth server url should be mutually exclusive, but at some point the implementation has diverged from that. In working on the PR, I encountered issues where oidc provider being set was insufficient, as there are upstream classes that check only the auth server url. Eventually I was having enough issues that I stopped looking into it in favor of implementing the requirements for the PR; I think a component of this issue is going through the properties used and making sure their uses are consistent (e.g. [KeycloakServiceClient](https://github.com/eclipse/che/blob/a59db0a176a82387c78b76201d42050960acced6/multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/KeycloakServiceClient.java#L103) will throw an NPE if oidc provider is set and auth server url is not).

**Comment by davidfestal** [comment]
> I encountered issues where oidc provider being set was insufficient, as there are upstream classes that check only the auth server url. Eventually I was having enough issues that I stopped looking into it in favor of implementing the requirements for the PR; I think a component of this issue is going through the properties used and making sure their uses are consistent (e.g. KeycloakServiceClient will throw an NPE if oidc provider is set and auth server url is not).

#### A bit of history

Yes, in fact the main problem seems to come from the fact that initial OAuth-based account linking code (see eclipse/che@8ff1be3) was written before the addition of basic OIDC-provider support (eclipse/che@ff3459d) in a way that was really specific to Keycloak.
It was then refactored in commit eclipse/che@d2fcdb7 to create the `KeycloakServiceClient`, but still always in a Keycloak-specific way.

And in my commit eclipse/che@ff3459d about OIDC providers support that came after, I should have added a support for the oidc-provider use-case, or at least I should have added a warning or an error when trying to access the Keycloak-specific account linking service while using alternate OIDC providers.

Then a last refactoring (eclipse/che@cd99cf4) introduced a new level of extension with the `OAuthApi`, but the `KeycloakServiceClient` is still Keycloak-only and no consistent `OAuthApi` implementation is selected in the case alternate OIDC providers are used.

#### What to do now ?

So it seems to me that the main thing to do would be to *__define, in upstream, how OAuth token linking is performed with alternate OIDC providers__* (=> when the `che-keycloak-oidc-provider` property is set). Since this use-case is *simply ignored* as for OAuth account linking.

#### Proposed way

Maybe simply allow properties like those proposed here: https://github.com/redhat-developer/rh-che/pull/810#pullrequestreview-150007372, but in upstream Che, and use them in the `KeycoakServiceClient` when the `che-keycloak-oidc-provider` property is used to build account linking urls):

```
# already existing property in `multiuser.properties`

che.oauth.service_mode=delegated

# proposed new optional properties:
# - 2 properties per linked identity provider (here github and openshift)
# - Only required when `che.keycloak.oidc_provider` is used instead of `che.keycloak.auth_server_url`
# When Keycloak is used they would be built by the Che code itself based on the keycloak settings
# as it is today

che.oauth.delegated.provider.github.endpoints.link=api/token/link?for=https://github.com
che.oauth.delegated.provider.github.endpoints.token=api/token?for=https://github.com

che.oauth.delegated.provider.openshift.endpoints.link=api/token/link?for=openshift
che.oauth.delegated.provider.openshift.endpoints.token=api/token?for=openshift
```
In fact this would somehow bring back, but as part of a consistent design, those following old properties that are not used anymore (afaict):
```
# Redhat che specific configuration

#     URL to access OSO oauth tokens
che.keycloak.oso.endpoint=NULL

#     URL to access Github oauth tokens
che.keycloak.github.endpoint=NULL
```

#### Conclusion

It seems that *the support of delegated OAuth account linking in the case of alternate OIDC providers should be in upstream Che*. And adding it based on the proposed properties would probably allow us to *fully remove or at least greatly simplify the specific implementation done in `rh-che` in this regard*.
Finally all would boil down to transferring part of @amisevsk work from `rh-che` to upstream Che.

**Comment by ibuziuk** [comment]
Closing as outdated
